### PR TITLE
Fix incorrect Accessor implementation

### PR DESCRIPTION
**Pull request by ChloeDawn**

### CODE REVIEW

**Comment by LemmaEOF** [comment]
Can you double-check this works? I remember trying to do this before but having issues with it actually working properly.

**Comment by ChloeDawn** [comment]
This is the correct form of an Accessor mixin, as described by the documentation. Accessor mixins within your mixin package can be referenced in non-mixin context.

**Comment by LemmaEOF** [comment]
Yes, I know it's the correct form, but *does it work in game?* I tried before and it *didn't*, so please actually run this to make sure it works before I merge it.

**Comment by ChloeDawn** [comment]
Well derp this change won't work anyway because I forgot to remove the removed Mixin from the config..

**Comment by ChloeDawn** [comment]
Can confirm the game launches fine

**Comment by LemmaEOF** [comment]
Alright, I'll merge it in and test it out some more. I remember a couple times it only started crashing when I hit myself with a tipped arrow.

**Pull request merged**
